# Generated by Django 5.0.4 on 2024-07-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField(null=True)),
                ('isbn', models.CharField(db_index=True, max_length=13, unique=True)),
                ('pages', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
